{
    "type": [
        2,
        2,
        0,
        1,
        0,
        1,
        0,
        0,
        1,
        0,
        1,
        0,
        0,
        1,
        0,
        1,
        2,
        0,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        3,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        3,
        0,
        1,
        3,
        3,
        0,
        1,
        0,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        0,
        1,
        0,
        1,
        3,
        0,
        1,
        3,
        2
    ],
    "data": [
        "\nR Under development (unstable) (2025-02-21 r87787 ucrt) -- \"Unsuffered Consequences\"\nCopyright (C) 2025 The R Foundation for Statistical Computing\nPlatform: x86_64-w64-mingw32/x64\n\nR is free software and comes with ABSOLUTELY NO WARRANTY.\nYou are welcome to redistribute it under certain conditions.\nType 'license()' or 'licence()' for distribution details.\n\n  Natural language support but running in an English locale\n\nR is a collaborative project with many contributors.\nType 'contributors()' for more informa",
        "tion and\n'citation()' on how to cite R or R packages in publications.\n\nType 'demo()' for some demos, 'help()' for on-line help, or\n'help.start()' for an HTML browser interface to help.\nType 'q()' to quit R.\n\n",
        "> ",
        "# Example dataset",
        "> ",
        "data(iris)",
        "> ",
        "> ",
        "# Fit an ANOVA model",
        "> ",
        "model <- aov(Sepal.Length ~ Species, data = iris)",
        "> ",
        "> ",
        "# Get marginal means",
        "> ",
        "emmeans::emmeans(model, ~ Species)",
        " Species    emmean     SE  df lower.CL upper.CL\n setosa       5.01 0.0728 147     4.86     5.15\n versicolor   5.94 0.0728 147     5.79     6.08\n virginica    6.59 0.0728 147     6.44     6.73\n\nConfidence level used: 0.95 \n",
        "> ",
        "> ",
        "emmeans::emmip(name~Group)",
        "Error in emmip.default(name ~ Group) : \n  argument \"formula\" is missing, with no default\n",
        "> ",
        "emmeans::emmip(model, ~Species)",
        "> ",
        "reticulate::repl_python()",
        "Error in python_config_impl(python) : \n  Error 103 occurred running C:/Users/samon/OneDrive/Documents/.virtualenvs/r-reticulate/Scripts/python.exe: \nIn addition: Warning message:\nIn system2(command = python, args = shQuote(script), stdout = TRUE,  :\n  running command '\"C:/Users/samon/OneDrive/Documents/.virtualenvs/r-reticulate/Scripts/python.exe\" \"C:/Users/samon/AppData/Local/R/win-library/4.5/reticulate/config/config.py\"' had status 103\nError in py_discover_config(required_module, use_environment) : \n  Py",
        "thon specified in RETICULATE_PYTHON (D:/Programs/Anaconda/python.exe) does not exist\n",
        "> ",
        "reticulate::py_config()",
        "Error in py_discover_config(required_module, use_environment) : \n  Python specified in RETICULATE_PYTHON (D:/Programs/Anaconda/python.exe) does not exist\n",
        "> ",
        "reticulate::py_config(\"C:\\Users\\samon\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe\")",
        "Error: '\\U' used without hex digits in character string (<input>:1:27)\n",
        "> ",
        "reticulate::py_config(r\"(C:\\Users\\samon\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe)\")",
        "Error in reticulate::py_config(\"C:\\\\Users\\\\samon\\\\AppData\\\\Local\\\\Microsoft\\\\WindowsApps\\\\python.exe\") : \n  unused argument (\"C:\\\\Users\\\\samon\\\\AppData\\\\Local\\\\Microsoft\\\\WindowsApps\\\\python.exe\")\n",
        "> ",
        "?reticulate::py_config()",
        "> ",
        "reticulate::use_python(\"C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe\", required = TRUE)",
        "Warning messages:\n1: In file.info(x, extra_cols = FALSE) :\n  cannot open file 'C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe': The file cannot be accessed by the system\n2: In file.info(x, extra_cols = FALSE) :\n  cannot open file 'C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe': The file cannot be accessed by the system\n3: The request to `use_python(\"C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe\")` will be ignored because the environment variable RETICULATE_PYTH",
        "ON is set to \"D:/Programs/Anaconda/python.exe\" \n",
        "> ",
        "reticulate::use_python(\"C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe\", required = TRUE)",
        "Warning messages:\n1: In file.info(x, extra_cols = FALSE) :\n  cannot open file 'C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe': The file cannot be accessed by the system\n2: In file.info(x, extra_cols = FALSE) :\n  cannot open file 'C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe': The file cannot be accessed by the system\n3: The request to `use_python(\"C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe\")` will be ignored because the environment variable RETICULATE_PYTH",
        "ON is set to \"D:/Programs/Anaconda/python.exe\" \n",
        "> ",
        "file.edit(\"~/.Renviron\")",
        "> ",
        "> ",
        "Sys.unsetenv(\"RETICULATE_PYTHON\")",
        "> ",
        "reticulate::use_python(NULL)",
        "Error in file.info(x, extra_cols = FALSE) : invalid filename argument\n",
        "> ",
        "Sys.unsetenv(\"RETICULATE_PYTHON\")",
        "> ",
        "reticulate::use_python(\"C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe\", required = TRUE)",
        "Warning messages:\n1: In file.info(x, extra_cols = FALSE) :\n  cannot open file 'C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe': The file cannot be accessed by the system\n2: In file.info(x, extra_cols = FALSE) :\n  cannot open file 'C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe': The file cannot be accessed by the system\n",
        "> ",
        "py_config()",
        "Error in py_config() : could not find function \"py_config\"\n",
        "> ",
        "Sys.unsetenv(\"RETICULATE_PYTHON\")",
        "> ",
        "reticulate::use_python(\"C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe\", required = TRUE)",
        "Warning messages:\n1: In file.info(x, extra_cols = FALSE) :\n  cannot open file 'C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe': The file cannot be accessed by the system\n2: In file.info(x, extra_cols = FALSE) :\n  cannot open file 'C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe': The file cannot be accessed by the system\n",
        "> ",
        "reticulate::py_config()",
        "Error: C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.12_3.12.2544.0_x64__qbz5n2kfra8p0/python312.dll - Access is denied.\r\nIn addition: Warning message:\nIn file.info(x, extra_cols = FALSE) :\n  cannot open file 'C:/Users/samon/AppData/Local/Microsoft/WindowsApps/python.exe': The file cannot be accessed by the system\n",
        "\nRestarting R session...\n\n"
    ]
}